### ISSUE TITLE
Working on Sync:  Missing Match, strange events

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#167]
Hi Greg,

I'm trying to make some progress on sync again.

For a simple example (see patterns and models attached), I expect to get an insert event for ```IgnoreFamily__FWD```.  This is, however, not produced.

Instead I get a series of insert and delete events for ```HandleRegisters__FWD```.  This is rather confusing -- why am I getting insert/delete events?  Is this normal and to be expected (apart from the missing match which is certainly a problem)?  Would you expect in this case to get numerous insert/delete events that "sum" up to no match for  ```HandleRegisters__FWD``` (which actually shouldn't match at all)?

Please tell me if you have problems reproducing...  I could try to export a fat jar so you can actually run the forward synchronisation as we do.

Cheers and thanks,
Tony

[missingMatch.zip](https://github.com/eMoflon/emoflon-ibex/files/981202/missingMatch.zip)

**Comment by anthonyanjorin** [comment]
ok - this might have something to do with missing injectivity checks.

**Comment by anthonyanjorin** [comment]
However the question regarding multiple inserts and deletes is still open.

**Comment by anthonyanjorin** [comment]
Hi Greg,

I've now added all injectivity checks that I believe should be present.  Unfortunately, I'm still not getting the expected match.

Please find the updated patterns attached.

[missingMatch.zip](https://github.com/eMoflon/emoflon-ibex/files/983805/missingMatch.zip)

**Comment by gervarro** [comment]
Hi Tony,

could you please tell me which test case produces these strange events?

Bests,
Greg

**Comment by anthonyanjorin** [comment]
Hi Greg,

if `https://github.com/eMoflon/emoflon-ibex/blob/master/org.emoflon.ibex.tgg.tests/testsuite2_familiestopersons/test/testsuite1/familiestopersons/sync/batch/BatchForward.java` is running then I would be happy for the moment.

When you run the tests, you'll notice that I print out all events that are produced on the console.  

I'll continue writing more tests and if they fail then I'll open a new issue.

Cheers,
Tony

**Comment by anthonyanjorin** [comment]
I just updated and tried out `testMotherToFemale()`.  It's still failing as no matches for the pattern `CreateMotherInNewFamily__FWD` are found (and I don't understand why not).  This can of course be a bug on my side, but the pattern network actually looks ok to us.

**Comment by gervarro** [comment]
Hi Tony,

I analyzed the `testMotherToFemale` test case in the `testsuite2_familiestopersons` project, and now I summarize my experience:
- There was a bug in the pattern matcher. The fix will be available next week (hopefully together with the fixes for the "Join failed" exception).
- After carrying out the fix locally, the pattern matcher produces the expected match, but the test still fails as the forward transformation does not set the `name` attribute for the newly created `Female` object.
- The `EMFPatternBuilder` has also a `build` method that can process multiple patterns in one turn, which is typically a better solution instead of invoking the other `build` method with a single pattern as parameter. I would recommend updating the `DemoclesHelper` class at line 129.

Regarding the superfluous sequence of insert/delete events: I know that I suggested the use of the `handleEvent` method, but it is a pattern matcher internal method, which should be replaced by something else in the future that could better play the role of a public API. The pattern matcher already produces a data structure that "sums up" the events (for each pattern) in the expected manner. This data structure is not yet available on the public interface, but it will definitely change in the future.

The other topic that I wanted to mention is that the CSPs could also be handled by the pattern matcher, which would offer an automated incremental re-evaluation, if I remember correctly.

The next bug to be fixed is #150.

Bests,
Greg

**Comment by anthonyanjorin** [comment]
Hi Greg,

happy to see that our usage in Ibex is revealing some bugs in Democles.
I've created issues from all your tips -- thanks!

Cheers,
Tony

**Comment by gervarro** [comment]
Hi Tony,

it is not a surprise as these pattern invocations have never been so widely used as in the Ibex scenario. The fix for the "Join failed" exception bug will be online at latest tomorrow evening. 3 tests still fail after the fix (one even producing an infinite loop), but the reason for these failing tests is not a runtime exception any more. I will analyze the failing tests in the next couple days.

Bests,
Greg
