### ISSUE TITLE
Double-checking request for Ibex rule to Democles pattern mapping

### ISSUE THREAD

**Issue by gervarro** [eMoflon/emoflon-ibex#190]
Hi Tony,

while fixing the "Join failed" exception bug(s), I experienced some unexpected setups. Could you please check whether they represent the intended behaviour?

- The `ConnectFather__CONTEXT_SRC/3` pattern is disjoint (first two and second two symbolic parameters are not connected).
- There was a case represented by the `ConnectFather` rule and `0 - f__father__father_eMoflonEdge TGGRuleEdge(SRC,CREATE)` when a 0..1 reference was set to an identical value. Can it happen that the TGG engine explicitly sets a value even if it does not change?

Bests,
Greg

**Comment by anthonyanjorin** [comment]
@FStolte Let's discuss this tomorrow if you're available

**Comment by FStolte** [comment]
Short answer: 1. Yes, and 2. Sort of yes.

Long answer:
The disjoint pattern is desired. The ConnectFather rule adds an edge between a Father and a Family. So the pattern just contains those two nodes (and the FamilyRegister which the Family belongs to), which are not yet connected.
However, for me the pattern has just three parameters, not four. If that was not only a typo and you really have four parameters in that pattern, then something is surely wrong...
/edit: Nevermind, I think I just understood what you meant with first two and second two parameters, so everything should be fine with the first case.

Now, currently it is possible that a 0..1 reference is set to the identical value in this special case. This, however, is unnecessary and I will probably be able to remove it soon. Nevertheless, I would expect that this has no effect on the pattern matching. If it might cause problems somewhere along the line, then please explain this to me so that I can deliberately avoid setting identical values of references in the future.

Bests,
Florian

**Comment by gervarro** [comment]
Hi,

> The disjoint pattern is desired.

OK. I just wanted to be sure that this case was not a bug.

> Now, currently it is possible that a 0..1 reference is set to the identical value in this special case. This, however, is unnecessary and I will probably be able to remove it soon. Nevertheless, I would expect that this has no effect on the pattern matching. If it might cause problems somewhere along the line, then please explain this to me so that I can deliberately avoid setting identical values of references in the future.

It should not be a problem theoretically, but EMF issues a notification if a 0..1 reference is set to an identical value, which was not handled appropriately until the latest version, which is now available on the 2 update sites.

Bests,
Greg
