### ISSUE TITLE
require context nodes in protocol patterns

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-ibex#194]
... and not only created nodes to identify rule applications uniquely.

This bug has the following consequence: When we have a rule that does not create a node (but only edges), the protocol node in the pattern is not connected to any model element at all.

**Comment by anthonyanjorin** [comment]
Solution:

We need a new type of patterns of the form:  [ protocolNode---contextSrc/Trg---> foo ]

These new patterns have to be integrated to protocol patterns.

**Comment by Arikae** [comment]
Not sure if I'm doing something terribly wrong but implementing this dramatically increases the execution times of our sync tests, e.g. BlockDiagram: before 3-6s after 90-...s

**Comment by anthonyanjorin** [comment]
Have you profiled to find out what the problem is?  I don't understand my solution anymore but maybe it's not a good idea to have so many patterns, i.e., we should go for one larger pattern.

I'm not 100% sure, but perhaps we could also inspect the rule and only create these extra pattern if it's a pure edge rule (ask @erhanleblebici).

But profiling to locate the hotspot would be a good idea in any case.

**Comment by anthonyanjorin** [comment]
If I understand corrrectly this was implemented as one larger pattern.  Perhaps many smaller patterns (like for marked elements) would be better.  Have to try it out or ask Greg for advice.

**Comment by anthonyanjorin** [comment]
Looks as though this is now working as separate small patterns.  It has slowed things down a bit, don't get me wrong, but not so terribly and all tests run without out-of-memory exceptions.

I suggest we go with this solution and optimise things from here.
