### ISSUE TITLE
Add incremental parts to the API

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#289]
Right now the API is rather standard.  More interesting would be support for things that only an incremental pattern matcher can support.

Please brainstorm a bit and think out of the box :)

Here are some ideas:

- ```whenMatchAppears(Consumer<M> c)```
- ```whenMatchDisappears(M match, Runnable r)```
- ???

**Comment by patrickrobrecht** [comment]
As we only have simple constraints so far, the model cannot be changed via graph transformation and therefore the set of matches will be constant after the initial loading. So I don't really understand why such listeners for new/disappeared matches should be relevant before adding/deleting is implemented: You simply would not get any notifications except for the matches you can access via `findMatches()`.

**Comment by anthonyanjorin** [comment]
Easy:  I can change the model myself via the normal EMF API :)

**Comment by anthonyanjorin** [comment]
A simple scenario:  I have a pattern defining the end of the game (all characters on an exit or whatever), and I want to transition to the next puzzle as soon as a match is found.  Doesn't that make sense?  In general, I might not want to use GT for everything...  especially if the user is actually changing the models directly...

**Comment by patrickrobrecht** [comment]
My first thoughts on this: `whenMatchAppears(Consumer<M> c)` subscribes all new matches for a certain pattern, we may provide the possibility to unsubscribe the notifications later if you are not interested in new matches anymore.

- `subscribeNewMatchNotifications(Consumer<M> c)`
- `unsubscribeNewMatchNotifications(Consumer<M> c)`
- `subscribeDisappearingMatchNotifications(Consumer<M> c)`
- `unsubscribeDisappearingMatchNotifications(Consumer<M> c)`

The `GraphTransformationInterpreter` would manage the subscriptions for new/disappearing matches of a certain pattern and whenever a new match appears/disappears, it checks whether someone subscribed the notifications for that pattern and if yes, it calls the `Consumer`'s `accept` method for the match.

To get a notification if a specific match disappears, `whenMatchDisappears(M match, Runnable r)` is fine. Maybe we should use a `Consumer` here as well: If you register the same `Runnable` for disappearing match notifications of different matches, you would not get the information which match exactly disappeared otherwise.

**Comment by anthonyanjorin** [comment]
Makes sense - to keep the methods shorter we could use:

- subscribeAppearing(Consumer)
- unsubscribeAppearing(Consumer)
- subscribeDisappearing(Consumer)
- unsubscribeDisappearing(Consumer)
- whenMatchDisappears(Consumer)

We could postpend „Matches“ to the first four methods, but I don’t really think it’s necessary.

With some experience one could decide if methods with the number of appeared matches are useful or not.  For now I would suggest we stay minimal until we’ve used the API a bit more.
