### ISSUE TITLE
CO strategy falsely says models are inconsistent / circle detection for multi-amalgamation

### ISSUE THREAD

**Issue by RobinOppermann** [eMoflon/emoflon-ibex#308]
All required matches are found by the strategy, but an exclusion for the ILP is defined resulting in not being able to choose the correct match.
This is because a cycle is detected between a kernel and complement even though there should not be one.
CC works because in CC there is no cycle detected.

**Comment by RobinOppermann** [comment]
[ExampleCObug.zip](https://github.com/eMoflon/emoflon-ibex/files/1833613/ExampleCObug.zip)

**Comment by smilicas** [comment]
The problem arises because complement rule match is collected in the bundle with the kernel that it does not belong to. Assumption that we had before (that is also implemented in the code) is that the complement rule match is available only after its "parent" kernel is applied (OPT.java, line 321), however this temporal assumption shown to be wrong. 
Suggestion for updating the implementation: collect all kernel matches, apply them, then collect all available complement rule matches apply  and join them to correct bundles with their "parent" kernels (this is important for detecting cyclic dependencies between bundles), then switch to kernel matches again... 
Important note: when collecting complement rule matches to be aware of uniqueness among them (same CR match cannot be collected in the same bundle twice) in order to generated proper uniqueness constraints.

p.s. I think method handleMaximality() (CC.java, 118) can be removed as it was implemented before, trying to handle the same think cyclic dependencies are handling.

**Comment by anthonyanjorin** [comment]
We should also try first to remove all code handling „maximality“.  This is supposedly obsolete anyway.

**Comment by anthonyanjorin** [comment]
Some updates:  
- The maximality check is required after all.
- The problem here is (as the title already clearly states) only a problem for CO.
- The reason that the temporal assumption for collecting bundles correctly is violated, is because CO patterns are simply WHOLE patterns without any additional structure for amalgamation.  What we have to do is perhaps create CO patterns that are amalgamation-aware, i.e., complement patterns for CO should demand the consistency pattern of their kernel (similar to CC).
